### ISSUE TITLE
Add a pdf compilation of paper.tex

### ISSUE THREAD

**Issue by AyoubBelhadji** [CRIStAL-Sigma/reproducible-paper#6]
It will be nice if we can get a pdf version of the article somewhere in the repo.

**Comment by guilgautier** [comment]
Good point @AyoubBelhadji !
I am going to use Travis to build the `.tex` and deploy the `.pdf` ;)

**Comment by guilgautier** [comment]
Done https://github.com/CRIStAL-Sigma/reproducible-paper/releases/tag/v1.0 😃
